### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by arshu-dev** [ooper-shlab/DocInteraction1.6-Swift#1]
Not working after update to Swift 3.0, Xcode 8.0. Please update the code compatible to Swift 3.0

**Comment by ooper-shlab** [comment]
I cannot promise anything except that I put this project on top of my migrate-to-Swift3 queue. Please wait with patience.

**Comment by ooper-shlab** [comment]
Done. Please try.

**Comment by arshu-dev** [comment]
Sorry for the late reply. Thanks it is working fine now. 👍
